#! /bin/bash -e

EJEMPLOS=~/Latex-Configuracion-Manual/Ejemplos
curr_dir=`pwd`

PROMPT=">> "

nombre=$1

echo -e "\e[1;36m¿Cuál ejemplo quieres que mueva?\e[0m"
ls $EJEMPLOS

read -p "${PROMPT}" ejemplo 

if [ -z $ejemplo ] ; then 
    ejemplo=Algebra
elif [ ! -e ${EJEMPLOS}/${ejemplo} ] ; 
then
    ejemplo=Algebra
fi

no_de_tareas=`ls | wc -l`
no_de_tareas=$((no_de_tareas+1))

echo -e "\e[1;36mCopiando $ejemplo\e[0m"
cp -r $EJEMPLOS/$ejemplo $curr_dir/Tarea${no_de_tareas}
