#!/bin/python

import argparse

parser = argparse.ArgumentParser("")

# Arguments
parser.add_argument(
    '--foo',
    dest = 'foo',
    help = "foo of the %(prog)s program"
)

args = parser.parse_args()

